# permissions for end users to view crdrefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: crdref-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tmp
    app.kubernetes.io/part-of: tmp
    app.kubernetes.io/managed-by: kustomize
  name: crdref-viewer-role
rules:
- apiGroups:
  - cache.bitspur.com
  resources:
  - crdrefs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.bitspur.com
  resources:
  - crdrefs/status
  verbs:
  - get
