# permissions for end users to edit crdrefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: crdref-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tmp
    app.kubernetes.io/part-of: tmp
    app.kubernetes.io/managed-by: kustomize
  name: crdref-editor-role
rules:
  - apiGroups:
      - cache.rock8s.com
    resources:
      - crdrefs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cache.rock8s.com
    resources:
      - crdrefs/status
    verbs:
      - get
